spring.application.name=InkRedPlumesBackend

# PORT SERVEUR
server.port=8080

# CONNEXION BDD MARIA DB
spring.datasource.url=jdbc:mariadb://localhost:3306/ink_red_plumes
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# CONFIG JPA / HIBERNATE
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

# CHARSET
spring.datasource.hikari.connection-init-sql=SET NAMES utf8mb4

# CONFIG DEVTOOLS (rechargement automatique)
spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true
